# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('job_position', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('hours_per_week', models.IntegerField()),
                ('where_found_us', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('english_level', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
